#%RAML 1.0 NamedExample
value: 

  -
    name: "Leo"
    type: business
    address: "345 Green St, Boulder, Colorado,45781,USA"
    airMiles: 4
  -
    name: "Williams"
    type: personal
    address: "89 Main St, Springfield, Illinois, 62301, USA"
    airMiles: 5
    
